# -------------------------------------------------------------------------------
# buildAOVModel: Functions for building model in ANOVA
# Created by: Alaine A. Gulles for International Rice Research Institute
# -------------------------------------------------------------------------------

buildAOVModel <- function(design, respvar, factor1, factor2 = NULL, factor3 = NULL, 
                          factor4 = NULL, rep1 = NULL, rep2 = NULL, set =  NULL) UseMethod("buildAOVModel")

buildAOVModel.default <- function(design, respvar, factor1, factor2 = NULL, factor3 = NULL, 
                          factor4 = NULL, rep1 = NULL, rep2 = NULL, set =  NULL) {
     
     availableDesign <- c("CRD", "RCBD", "LSD", "SplitCRD", "SplitRCBD", "SplitLSD", "Strip", "Split2CRD", "Split2RCBD", "Split2LSD", "Strip-Split",     "Split3CRD", "Split3RCBD", "Split3LSD", "Strip-Split2")
     if(is.na(match(design, availableDesign))) {
          stop("Design must be one of the following:\n'CRD', 'RCBD', 'LSD',\n'SplitCRD', 'SplitRCBD', 'SplitLSD','Strip',\n'Split2CRD', 'Split2RCBD', 'Split2LSD', 'Strip-Split',\n'Split3CRD', 'Split3RCBD', 'Split3LSD', 'Strip-Split2'")
     }
     
     designChoice <- match(design, availableDesign) ## design code
     
     if (is.null(set)) {
          switch(designChoice,
               {numfactor <- 1; numblk <- 0; modelRHS <- paste(paste(factor1, collapse = "*", sep = "")); modelRHS2 <- modelRHS},
               {numfactor <- 1; numblk <- 1; modelRHS <- paste(rep1, " + ", paste(factor1, collapse = "*", sep = ""), sep = ""); modelRHS2 <- modelRHS},
               {numfactor <- 1; numblk <- 2; modelRHS <- paste(rep1, " + ", rep2, " + ", paste(factor1, collapse = "*", sep = ""), sep = ""); modelRHS2 <- modelRHS},
               {numfactor <- 2; numblk <- 1; modelRHS <- paste(paste(c(factor1, factor2), collapse = "*", sep = ""), " + Error((", paste(c(rep1, factor1), collapse = ":", sep = "") , ")/",  rep1, ")", sep = "");
                modelRHS2 <- paste(paste(c(factor1, factor2), collapse = "*", sep = ""), " + ", paste(c(rep1, factor1), collapse = ":", sep = ""), sep = "")},
               {numfactor <- 2; numblk <- 1; modelRHS <- paste(rep1 ," + ", paste(c(factor1, factor2), collapse = "*", sep = ""), " + Error(", paste(c(rep1, factor1), collapse = ":", sep = ""), "/(", paste(factor1, collapse = ":", sep = ""), "))", sep = "");
                modelRHS2 <- paste(rep1 ," + ", paste(c(factor1, factor2), collapse = "*", sep = ""), " + ", paste(c(rep1, factor1), collapse = ":", sep = ""), sep = "")},
               {numfactor <- 2; numblk <- 2; modelRHS <- paste(rep1 ," + ", rep2 ," + ", paste(c(factor1, factor2), collapse = "*", sep = ""), " + Error(", paste(c(rep1,rep2, factor1), collapse = ":", sep = ""), "/(", paste(factor1, collapse = "*", sep = ""), "))", sep = "");
                modelRHS2 <- paste(rep1 ," + ", rep2 ," + ", paste(c(factor1, factor2), collapse = "*", sep = ""), " + ", paste(c(rep1,rep2, factor1), collapse = ":", sep = ""), sep = "")},
               {numfactor <- 2; numblk <- 1; modelRHS <- paste(rep1 ," + ", paste(c(factor1, factor2), collapse = "*", sep = ""), " + Error((", paste(c(rep1,factor1), collapse = ":", sep = ""), "/", paste(factor1, collapse = ":", sep = ""), ") + (", paste(c(rep1, factor2), collapse = ":", sep = ""), "/", paste(factor2, collapse = ":", sep = ""), "))", sep = "");
                modelRHS2 <- paste(rep1 ," + ", paste(c(factor1, factor2), collapse = "*", sep = ""), " + ", paste(c(rep1,factor1), collapse = ":", sep = ""), " + ", paste(c(rep1, factor2), collapse = ":", sep = ""), sep = "")},
               {numfactor <- 3; numblk <- 1; modelRHS <- paste(paste(c(factor1, factor2, factor3), collapse = "*", sep = ""), " + Error((", paste(c(rep1, factor1), collapse = ":", sep = ""), "/", rep1, ") + (", paste(c(rep1, factor1, factor2), collapse = ":", sep = ""), "/", paste(factor2, collapse = ":", sep = ""), "))", sep = "");
                modelRHS2 <- paste(paste(c(factor1, factor2, factor3), collapse = "*", sep = ""), " + ", paste(c(rep1, factor1), collapse = ":", sep = ""), " + ", paste(c(rep1, factor1, factor2), collapse = ":", sep = ""), sep = "")},
               {numfactor <- 3; numblk <- 1; modelRHS <- paste(rep1 ," + ", paste(c(factor1, factor2, factor3), collapse = "*", sep = ""), " + Error((", paste(c(rep1, factor1), collapse = ":", sep = ""), "/", paste(factor1, collapse = ":", sep = ""), ") + (", paste(c(rep1, factor1, factor2), collapse = ":", sep = ""), "/", paste(factor2, collapse = ":", sep = ""), "))", sep = "");
                modelRHS2 <- paste(rep1 ," + ", paste(c(factor1, factor2, factor3), collapse = "*", sep = ""), " + ", paste(c(rep1, factor1), collapse = ":", sep = ""), " + ", paste(c(rep1, factor1, factor2), collapse = ":", sep = ""), sep = "")},
               {numfactor <- 3; numblk <- 2; modelRHS <- paste(rep1 ," + ", rep2 ," + ",paste(c(factor1, factor2, factor3), collapse = "*", sep = ""), " + Error((", paste(c(rep1, rep2, factor1), collapse = ":", sep = ""), "/", paste(factor1, collapse = ":", sep = ""), ") + (", paste(c(rep1, rep2, factor1, factor2), collapse = ":", sep = ""), "/", paste(factor2, collapse = ":", sep = ""), "))", sep = "");
                modelRHS2 <- paste(rep1 ," + ", rep2 ," + ",paste(c(factor1, factor2, factor3), collapse = "*", sep = ""), " + ", paste(c(rep1, rep2, factor1), collapse = ":", sep = ""), " + ", paste(c(rep1, rep2, factor1, factor2), collapse = ":", sep = ""), sep = "")},
               {numfactor <- 3; numblk <- 1; modelRHS <- paste(rep1 ," + ", paste(c(factor1, factor2, factor3), collapse = "*", sep = ""), " + Error((", paste(c(rep1, factor1), collapse = ":", sep = ""), "/", paste(factor1, collapse = ":", sep = ""), ") + (", paste(c(rep1, factor2), collapse = ":", sep = ""), "/", paste(factor2, collapse = ":", sep = ""), ") + (", paste(c(rep1, factor1, factor2), collapse = ":", sep = ""), "/", paste(c(factor1, factor2), collapse = ":", sep = ""),"))", sep = "");
                modelRHS2 <- paste(rep1 ," + ", paste(c(factor1, factor2, factor3), collapse = "*", sep = ""), " + ", paste(c(rep1, factor1), collapse = ":", sep = ""), " + ", paste(c(rep1, factor2), collapse = ":", sep = ""), " + ", paste(c(rep1, factor1, factor2), collapse = ":", sep = ""), sep = "")},
               {numfactor <- 4; numblk <- 1; modelRHS <- paste(paste(c(factor1, factor2, factor3, factor4), collapse = "*", sep = ""), " + Error((", paste(c(rep1, factor1), collapse = ":", sep = ""), "/", rep1, ") + (", paste(c(rep1, factor1, factor2), collapse = ":", sep = ""), "/", rep1, ") + (", paste(c(rep1, factor1, factor2, factor3), collapse = ":", sep = ""), "/", paste(factor3, collapse = ":", sep = ""), "))", sep = "");
                modelRHS2 <- paste(paste(c(factor1, factor2, factor3, factor4), collapse = "*", sep = ""), " + ", paste(c(rep1, factor1), collapse = ":", sep = ""), " + ", paste(c(rep1, factor1, factor2), collapse = ":", sep = ""), " + ", paste(c(rep1, factor1, factor2, factor3), collapse = ":", sep = ""), sep = "")},
               {numfactor <- 4; numblk <- 1; modelRHS <- paste(rep1 ," + ", paste(c(factor1, factor2, factor3, factor4), collapse = "*", sep = ""), " + Error((", paste(c(rep1, factor1), collapse = ":", sep = ""),         "/", paste(factor1, collapse = ":", sep = ""), ") + (", paste(c(rep1, factor1, factor2), collapse = ":", sep = ""),         "/", paste(factor2, collapse = ":", sep = ""), ") + (", paste(c(rep1, factor1, factor2, factor3), collapse = ":", sep = ""), "/", paste(factor3, collapse = ":", sep = ""), "))", sep = "");
                modelRHS2 <- paste(rep1 ," + ", paste(c(factor1, factor2, factor3, factor4), collapse = "*", sep = ""), " + ", paste(c(rep1, factor1), collapse = ":", sep = ""), " + ", paste(c(rep1, factor1, factor2), collapse = ":", sep = ""), " + ", paste(c(rep1, factor1, factor2, factor3), collapse = ":", sep = ""), sep = "")},
               {numfactor <- 4; numblk <- 2; modelRHS <- paste(rep1 ," + ", rep2 ," + ", paste(c(factor1, factor2, factor3, factor4), collapse = "*", sep = ""), " + Error((", paste(c(rep1, rep2, factor1), collapse = ":", sep = ""), "/", paste(factor1, collapse = ":", sep = ""), ") + (", paste(c(rep1, rep2, factor1, factor2), collapse = ":", sep = ""), "/", paste(factor2, collapse = ":", sep = ""), ") + (", paste(c(rep1, rep2, factor1, factor2, factor3), collapse = ":", sep = ""), "/", paste(factor3, collapse = ":", sep = ""),"))", sep = "");
                modelRHS2 <- paste(rep1 ," + ", rep2 ," + ", paste(c(factor1, factor2, factor3, factor4), collapse = "*", sep = ""), " + ", paste(c(rep1, rep2, factor1), collapse = ":", sep = ""), " + ", paste(c(rep1, rep2, factor1, factor2), collapse = ":", sep = ""), " + ", paste(c(rep1, rep2, factor1, factor2, factor3), collapse = ":", sep = ""), sep = "")},
               {numfactor <- 4; numblk <- 1; modelRHS <- paste(rep1 ," + ", paste(c(factor1, factor2, factor3, factor4), collapse = "*", sep = ""), " + Error((", paste(c(rep1, factor1), collapse = ":", sep = ""), "/", paste(factor1, collapse = ":", sep = ""), ") + (", paste(c(rep1, factor2), collapse = ":", sep = ""), "/", paste(factor2, collapse = ":", sep = ""), ") + (", paste(c(rep1, factor1, factor2), collapse = ":", sep = ""), "/", paste(c(factor1, factor2), collapse = ":", sep = ""), ") + (", paste(c(rep1, factor1, factor2, factor3), collapse = ":", sep = ""), "/", paste(c(factor3), collapse = ":", sep = ""), "))", sep = "");
                modelRHS2 <- paste(rep1 ," + ", paste(c(factor1, factor2, factor3, factor4), collapse = "*", sep = ""), " + ", paste(c(rep1, factor1), collapse = ":", sep = ""), " + ", paste(c(rep1, factor2), collapse = ":", sep = ""), " + ", paste(c(rep1, factor1, factor2, factor3), collapse = ":", sep = ""), sep = "")}
          ) ## end switch statement     
     } else {
          switch(designChoice,
               { modelRHS <- paste(set, paste(factor1, collapse = "*", sep = ""), paste(set , paste("(",paste(factor1, collapse = "*", sep = ""),")", sep = ""), sep = ":"), sep = " + "); modelRHS2 <- modelRHS },
               { modelRHS <- paste(set, paste(set, rep1, sep = ":"), paste(factor1, collapse = "*", sep = ""), paste(set, paste("(",paste(factor1, collapse = "*", sep = ""),")", sep = ""), sep = ":"), sep = " + "); modelRHS2 <- modelRHS},
               { modelRHS <- paste(set, paste(set, rep1, sep = ":"), paste(set, rep2, sep =":"), paste(factor1, collapse = "*", sep = ""), paste(set , paste("(",paste(factor1, collapse = "*", sep = ""),")", sep = ""), sep = ":"), sep = " + "); modelRHS2 <- modelRHS },
               { modelRHS <- paste(set, paste(c(factor1, factor2), collapse = "*", sep = ""), paste(set, paste("(",paste(c(factor1, factor2), collapse = "*", sep = ""),")", sep = ""), sep = ":"), paste("Error((", paste(c(set, rep1, factor1), collapse = ":", sep = ""),")/", rep1,")", sep = ""),sep = " + ");
                 modelRHS2 <- paste(set, paste(c(factor1, factor2), collapse = "*", sep = ""), paste(set, paste("(",paste(c(factor1, factor2), collapse = "*", sep = ""),")", sep = ""), sep = ":"), sep = " + ") },
               { modelRHS <- paste(set, paste(set, rep1, sep = ":"), paste(c(factor1, factor2), collapse = "*", sep = ""), paste(set, paste("(",paste(c(factor1, factor2), collapse = "*", sep = ""),")", sep = ""), sep = ":"), paste("Error((", paste(c(set, rep1, factor1), collapse = ":", sep = ""),")/(", paste(factor1, collapse = "*", sep = ""),"))", sep = ""), sep = " + ");
                 modelRHS2 <- paste(set, paste(set, rep1, sep = ":"), paste(c(factor1, factor2), collapse = "*", sep = ""), paste(set, paste("(",paste(c(factor1, factor2), collapse = "*", sep = ""),")", sep = ""), sep = ":"), sep = " + ") },
               { modelRHS <- paste(set, paste(set, rep1, sep = ":"), paste(set, rep2, sep = ":"), paste(c(factor1, factor2), collapse = "*", sep = ""), paste(set, paste("(",paste(c(factor1, factor2), collapse = "*", sep = ""),")", sep = ""), sep = ":"), paste("Error((", paste(c(set, rep1, rep2, factor1), collapse = ":", sep = ""),")/(", paste(factor1, collapse = "*", sep = ""),"))", sep = ""), sep = " + ");
                 modelRHS2 <- paste(set, paste(set, rep1, sep = ":"), paste(set, rep2, sep = ":"), paste(c(factor1, factor2), collapse = "*", sep = ""), paste(set, paste("(",paste(c(factor1, factor2), collapse = "*", sep = ""),")", sep = ""), sep = ":"), sep = " + ") },
               { modelRHS <- paste(set, paste(set, rep1, sep = ":"), paste(c(factor1, factor2), collapse = "*", sep = ""), paste(set, paste("(",paste(c(factor1, factor2), collapse = "*", sep = ""),")", sep = ""), sep = ":"), paste("Error((", paste(c(set, rep1, factor1), collapse = ":", sep = ""),")/(", paste(factor1, collapse = "*", sep = ""),") + (", paste(c(set, rep1, factor2), collapse = ":", sep = ""),"/", paste(factor2, collapse = "*", sep = ""),"))", sep = ""), sep = " + ");
                 modelRHS2 <- paste(set, paste(set, rep1, sep = ":"), paste(c(factor1, factor2), collapse = "*", sep = ""), paste(set, paste("(",paste(c(factor1, factor2), collapse = "*", sep = ""),")", sep = ""), sep = ":"), sep = " + ") },
               { modelRHS <- paste(set, paste(c(factor1, factor2, factor3), collapse = "*", sep = ""), paste(set, paste("(",paste(c(factor1, factor2, factor3), collapse = "*", sep = ""),")", sep = ""), sep = ":"), paste("Error((", paste(c(set, rep1, factor1), collapse = ":", sep = ""),")/(",rep1,") + (", paste(c(set, rep1, factor1, factor2), collapse = ":", sep = ""),"/", paste(factor2, collapse = ":", sep = ""),"))", sep = ""), sep = " + "); 
                 modelRHS2 <- paste(set, paste(c(factor1, factor2, factor3), collapse = "*", sep = ""), paste(set, paste("(",paste(c(factor1, factor2, factor3), collapse = "*", sep = ""),")", sep = ""), sep = ":"), sep = " + ") },
               { modelRHS <- paste(set, paste(set, rep1, sep = ":"), paste(c(factor1, factor2, factor3), collapse = "*", sep = ""), paste(set, paste("(",paste(c(factor1, factor2, factor3), collapse = "*", sep = ""),")", sep = ""), sep = ":"), paste("Error((", paste(c(set, rep1, factor1), collapse = ":", sep = ""),")/(", paste(factor1, collapse = "*", sep = ""),") + (", paste(c(set, rep1, factor1, factor2), collapse = ":", sep = ""),"/", paste(factor2, collapse = ":", sep = ""),"))", sep = ""), sep = " + ");
                 modelRHS2 <- paste(set, paste(set, rep1, sep = ":"), paste(c(factor1, factor2, factor3), collapse = "*", sep = ""), paste(set, paste("(",paste(c(factor1, factor2, factor3), collapse = "*", sep = ""),")", sep = ""), sep = ":"), sep = " + ") },
               { modelRHS <- paste(set, paste(set, rep1, sep = ":"), paste(set, rep2, sep = ":"), paste(c(factor1, factor2, factor3), collapse = "*", sep = ""), paste(set, paste("(",paste(c(factor1, factor2, factor3), collapse = "*", sep = ""),")", sep = ""), sep = ":"), paste("Error((", paste(c(set, rep1, rep2, factor1), collapse = ":", sep = ""),")/(", paste(factor1, collapse = "*", sep = ""),") + (", paste(c(set, rep1, rep2, factor1, factor2), collapse = ":", sep = ""),"/", paste(factor2, collapse = ":", sep = ""),"))", sep = ""), sep = " + ");
                 modelRHS2 <- paste(set, paste(set, rep1, sep = ":"), paste(set, rep2, sep = ":"), paste(c(factor1, factor2, factor3), collapse = "*", sep = ""), paste(set, paste("(",paste(c(factor1, factor2, factor3), collapse = "*", sep = ""),")", sep = ""), sep = ":"), sep = " + ") },
               { modelRHS <- paste(set, paste(set, rep1, sep = ":"), paste(c(factor1, factor2, factor3), collapse = "*", sep = ""), paste(set, paste("(",paste(c(factor1, factor2, factor3), collapse = "*", sep = ""),")", sep = ""), sep = ":"), paste("Error((", paste(c(set, rep1, factor1), collapse = ":", sep = ""),")/(", paste(factor1, collapse = "*", sep = ""),") + (", paste(c(set, rep1, factor2), collapse = ":", sep = ""),"/", paste(factor2, collapse = "*", sep = ""),") + (", paste(c(set, rep1, factor1, factor2), collapse = ":", sep = ""),"/", paste(c(factor1, factor2), collapse = ":", sep = ""),"))", sep = ""), sep = " + ");
                 modelRHS2 <- paste(set, paste(set, rep1, sep = ":"), paste(c(factor1, factor2, factor3), collapse = "*", sep = ""), paste(set, paste("(",paste(c(factor1, factor2, factor3), collapse = "*", sep = ""),")", sep = ""), sep = ":"), sep = " + ") },
               { modelRHS <- paste(set, paste(c(factor1, factor2, factor3, factor4), collapse = "*", sep = ""), paste(set , paste("(",paste(c(factor1, factor2, factor3, factor4), collapse = "*", sep = ""),")", sep = ""), sep = ":"), paste("Error((", paste(c(set, rep1, factor1), collapse = ":", sep = ""),")/(",rep1,") + (", paste(c(set, rep1, factor1, factor2), collapse = ":", sep = ""),"/", paste(factor2, collapse = ":", sep = ""),") + (", paste(c(set, rep1, factor1, factor2, factor3), collapse = ":", sep = ""),"/", paste(factor3, collapse = ":", sep = ""),"))", sep = ""), sep = " + ");
                 modelRHS2 <- paste(set, paste(c(factor1, factor2, factor3, factor4), collapse = "*", sep = ""), paste(set , paste("(",paste(c(factor1, factor2, factor3, factor4), collapse = "*", sep = ""),")", sep = ""), sep = ":"), sep = " + ") },
               { modelRHS <- paste(set, paste(set, rep1, sep = ":"), paste(c(factor1, factor2, factor3, factor4), collapse = "*", sep = ""), paste(set, paste("(",paste(c(factor1, factor2, factor3, factor4), collapse = "*", sep = ""),")", sep = ""), sep = ":"), paste("Error((", paste(c(set, rep1, factor1), collapse = ":", sep = ""),")/(", paste(factor1, collapse = "*", sep = ""),") + (", paste(c(set, rep1, factor1, factor2), collapse = ":", sep = ""),"/", paste(factor2, collapse = ":", sep = ""),") + (", paste(c(set, rep1, factor1, factor2, factor3), collapse = ":", sep = ""),"/", paste(factor3, collapse = ":", sep = ""),"))", sep = ""), sep = " + ");
                 modelRHS2 <- paste(set, paste(set, rep1, sep = ":"), paste(c(factor1, factor2, factor3, factor4), collapse = "*", sep = ""), paste(set, paste("(",paste(c(factor1, factor2, factor3, factor4), collapse = "*", sep = ""),")", sep = ""), sep = ":"), sep = " + ") },
               { modelRHS <- paste(set, paste(set, rep1, sep = ":"), paste(set, rep2, sep = ":"), paste(c(factor1, factor2, factor3, factor4), collapse = "*", sep = ""), paste(set, paste("(",paste(c(factor1, factor2, factor3, factor4), collapse = "*", sep = ""),")", sep = ""), sep = ":"), paste("Error((", paste(c(set, rep1, rep2, factor1), collapse = ":", sep = ""),")/(", paste(factor1, collapse = "*", sep = ""),") + (", paste(c(set, rep1, rep2, factor1, factor2), collapse = ":", sep = ""),"/", paste(factor2, collapse = ":", sep = ""),") + (", paste(c(set, rep1, rep2, factor1, factor2, factor3), sep = ""),"/", paste(factor3, collapse = ":", sep = ""),"))", sep = ""), sep = " + ");
                 modelRHS2 <- paste(set, paste(set, rep1, sep = ":"), paste(set, rep2, sep = ":"), paste(c(factor1, factor2, factor3, factor4), collapse = "*", sep = ""), paste(set, paste("(",paste(c(factor1, factor2, factor3, factor4), collapse = "*", sep = ""),")", sep = ""), sep = ":"), sep = " + ") },
               { modelRHS <- paste(set, paste(set, rep1, sep = ":"), paste(c(factor1, factor2, factor3, factor4), collapse = "*", sep = ""), paste(set, paste("(",paste(c(factor1, factor2, factor3, factor4), collapse = "*", sep = ""),")", sep = ""), sep = ":"), paste("Error((", paste(c(set, rep1, factor1), collapse = ":", sep = ""),")/(", paste(factor1, collapse = "*", sep = ""),") + (", paste(c(set, rep1, factor2), collapse = ":", sep = ""),"/", paste(factor2, collapse = "*", sep = ""),") + (", paste(c(set, rep1, factor1, factor2), collapse = ":", sep = ""),"/",paste(c(factor1, factor2), collapse = ":", sep = ""),") + (", paste(c(set, rep1, factor1, factor2, factor3), collapse = ":", sep = ""),"/", paste(factor3, collapse = ":", sep = ""),"))", sep = ""), sep = " + ");
                 modelRHS2 <- paste(set, paste(set, rep1, sep = ":"), paste(c(factor1, factor2, factor3, factor4), collapse = "*", sep = ""), paste(set, paste("(",paste(c(factor1, factor2, factor3, factor4), collapse = "*", sep = ""),")", sep = ""), sep = ":"), sep = " + ") }
          ) ## end switch stmt
     } ## end if-else stmt
     
     modelLHS <- paste(respvar[1], "~")
     mymodel <- paste(modelLHS, modelRHS)
     mymodel2 <- paste(modelLHS, modelRHS2)
     
     return(list(model1 = mymodel, model2 = mymodel2, modelRHS = modelRHS, modelRHS = modelRHS))
     
}